homeassistant:
  enabled: false
  use_local_mount: false
  tunnel:
    enabled: false

pg-homeassistant:
    enabled: false

nodered:
  enabled: false

cert_manager:
  enabled: false
  clusterIssuer:
    staging:
      enabled: false
  certificate:
    staging:
      enabled: false

cert-manager:
  crds:
    enabled: false

drone_launcher:
  enabled: false
  ingress:
    enabled: false
  tunnel:
    enabled: false

qbittorrent:
  enabled: false

kubernetesDashboard:
  enabled: false

k8up:
  enabled: false
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  resticRepositoryPassword: minio123
  backend:
    s3:
      endpoint: http://home-server-minio.home-server:9000
      bucket: backups
      accessKeyIDSecretRef:
        name: home-server-minio
        key: root-user
      secretAccessKeySecretRef:
        name: home-server-minio
        key: root-password
    repoPasswordSecretRef:
      name: k8up-secrets
      key: RESTIC_REPOSITORY_PASSWORD

minio:
  enabled: false
  auth:
    rootUser: minio
    rootPassword: minio123

grafana:
  enabled: false

loki:
  enabled: false

alloy:
  enabled: false

prometheus:
  enabled: false

kuma:
  enabled: false
  tunnel:
    enabled: false
  ingress:
    enabled: false

ntfy:
  enabled: false
  tunnel:
    enabled: false

atuin:
  enabled: false
pg-atuin:
  enabled: false

pihole:
  enabled: false

nfs:
  enabled: false
